# Generated by Django 4.1.7 on 2023-03-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_assignment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='basic.department'),
        ),
    ]
