# Generated by Django 4.1.7 on 2023-03-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_assignment_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='department',
        ),
    ]
