# Generated by Django 4.1.7 on 2023-03-17 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_studentprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
