# Generated by Django 4.1.7 on 2023-03-17 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_delete_studentprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='user',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='answer',
            field=models.CharField(max_length=2000),
        ),
    ]
