# Generated by Django 4.1.7 on 2023-03-17 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_remove_assignment_user_alter_assignment_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
