# Generated by Django 4.1.7 on 2023-03-17 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Notes',
            new_name='Note',
        ),
    ]
